[package]
name = "sow-native"
version = "0.1.0"
edition = "2021"
description = "Shadows of War — Native Desktop Client"

[dependencies]
sow-core = { workspace = true }
sow-render = { workspace = true }
blade-graphics = { workspace = true }

log = { workspace = true }
env_logger = { workspace = true }
winit = "0.29.15"
