[workspace]
members = [
    "sow-core",
    "sow-render",
    "sow-net",
    "sow-client",
    "sow-server",
    "sow-ui",
    "sow-tools",
    "sow-relay",
    "sow-lang",
    "sow-map",
    "sow-site",
]
exclude = ["blade", "winit", "egui"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.31.0-beta.2"
rust-version = "1.85"
license = "AGPL-3.0-or-later"
repository = "https://github.com/ohsalmeron/shadows-of-war"

[workspace.dependencies]
bincode = "1.3.3"
bitfield = "0.17"
env_logger = "0.11"
log = "0.4"
raw-window-handle = "0.6"
serde_json = "1"
web-time = "1.1"
wyrand = "0.2"
egui = { version = "0.34", default-features = false }
egui_extras = { path = "egui/crates/egui_extras", default-features = false, features = ["svg", "image", "webp"] }
image = { version = "0.25.10", default-features = false, features = ["webp", "png"] }
sow-lang = { path = "sow-lang" }
sow-map = { path = "sow-map", default-features = false }
sow-ui = { path = "sow-ui" }
winit = { path = "winit/winit", features = ["android-native-activity"] }
brotli = "8.0.2"
crossbeam-channel = "0.5.15"
url = "2.5.8"
wasm-bindgen-futures = "0.4.50"
wasm-bindgen = "0.2.100"
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = "0.1.7"
console_log = "1.0"
web-sys = { version = "0.3.69", features = ["Window", "Document", "Element", "HtmlElement", "HtmlInputElement", "Navigator", "CssStyleDeclaration", "Node", "VisibilityState", "Location", "BinaryType", "Worker", "MessageEvent", "Storage"] }
js-sys = "0.3.69"
tokio = { version = "1.52.3", features = ["full"] }
tokio-tungstenite = { version = "0.20.1", features = ["rustls-tls-webpki-roots"] }
futures-util = "0.3"
redis = "0.27"
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
clap = { version = "4.4", features = ["derive"] }
toml = "0.8"
ehttp = { version = "0.5.0", default-features = false }
libm = "0.2.16"
axum = "0.8.9"
tower-http = { version = "0.6.10", features = ["fs", "compression-br", "cors"] }
futures-channel = "0.3"

[workspace.dependencies.blade-egui]
path = "blade/blade-egui"

[workspace.dependencies.blade-graphics]
path = "blade/blade-graphics"

[workspace.dependencies.blade-macros]
path = "blade/blade-macros"

[workspace.dependencies.bytemuck]
version = "1"
features = ["derive"]

[workspace.dependencies.serde]
version = "1"
features = ["derive", "rc"]

[workspace.dependencies.sow-core]
path = "sow-core"

[workspace.dependencies.sow-net]
path = "sow-net"

[workspace.dependencies.sow-render]
path = "sow-render"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.deploy]
inherits = "release"
lto = false
codegen-units = 16
strip = true

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[patch.crates-io]
egui = { path = "egui/crates/egui" }
