//! African geo entities. Coordinates are approximate historical heartlands.

use super::{geo_entity as e, GeoEntity};

pub static AFRICA: &[GeoEntity] = &[
    // --- Countries (modern) ---
    e!(Africa: "Morocco", Country, Modern, 31.8, -7.1, "ma"),
    e!(Africa: "Algeria", Country, Modern, 28.0, 2.6, "dz"),
    e!(Africa: "Tunisia", Country, Modern, 34.0, 9.5, "tn"),
    e!(Africa: "Libya", Country, Modern, 27.0, 17.0, "ly"),
    e!(Africa: "Egypt", Country, Modern, 26.8, 30.0, "eg"),
    e!(Africa: "Sudan", Country, Modern, 15.5, 30.5, "sd"),
    e!(Africa: "South Sudan", Country, Modern, 7.0, 30.0, "ss"),
    e!(Africa: "Eritrea", Country, Modern, 15.2, 39.0, "er"),
    e!(Africa: "Ethiopia", Country, Modern, 9.0, 39.5, "et"),
    e!(Africa: "Somalia", Country, Modern, 5.0, 46.0, "so"),
    e!(Africa: "Kenya", Country, Modern, 0.5, 37.9, "ke"),
    e!(Africa: "Tanzania", Country, Modern, -6.3, 35.0, "tz"),
    e!(Africa: "Uganda", Country, Modern, 1.3, 32.4, "ug"),
    e!(Africa: "DR Congo", Country, Modern, -2.9, 23.7, "cd"),
    e!(Africa: "Cameroon", Country, Modern, 5.7, 12.4, "cm"),
    e!(Africa: "Nigeria", Country, Modern, 9.1, 8.7, "ng"),
    e!(Africa: "Niger", Country, Modern, 17.6, 8.1, "ne"),
    e!(Africa: "Chad", Country, Modern, 15.4, 18.7, "td"),
    e!(Africa: "Mali", Country, Modern, 17.6, -4.0, "ml"),
    e!(Africa: "Senegal", Country, Modern, 14.5, -14.5, "sn"),
    e!(Africa: "Mauritania", Country, Modern, 20.3, -10.3, "mr"),
    e!(Africa: "Sierra Leone", Country, Modern, 8.5, -11.8, "sl"),
    e!(Africa: "Liberia", Country, Modern, 6.4, -9.4, "lr"),
    e!(Africa: "Ivory Coast", Country, Modern, 7.5, -5.5, "ci"),
    e!(Africa: "Ghana", Country, Modern, 7.9, -1.0, "gh"),
    e!(Africa: "Benin", Country, Modern, 9.6, 2.3, "bj"),
    e!(Africa: "Gabon", Country, Modern, -0.6, 11.6, "ga"),
    e!(Africa: "Angola", Country, Modern, -12.3, 17.5, "ao"),
    e!(Africa: "Zambia", Country, Modern, -13.5, 27.8, "zm"),
    e!(Africa: "Zimbabwe", Country, Modern, -19.0, 29.8, "zw"),
    e!(Africa: "Botswana", Country, Modern, -22.3, 24.7, "bw"),
    e!(Africa: "Namibia", Country, Modern, -22.0, 17.0, "na"),
    e!(Africa: "Mozambique", Country, Modern, -18.7, 35.5, "mz"),
    e!(Africa: "Madagascar", Country, Modern, -19.4, 46.7, "mg"),
    e!(Africa: "South Africa", Country, Modern, -29.0, 25.0, "za"),
    e!(Africa: "Central African Republic", Country, Modern, 6.6, 20.9, "cf"),
    // --- Tribes & peoples ---
    e!(Africa: "Berbers", Tribe, Ancient, 31.0, -5.0),
    e!(Africa: "Tuareg", Tribe, Medieval, 20.0, 2.0),
    e!(Africa: "Nubians", Tribe, Ancient, 18.0, 31.0),
    e!(Africa: "Zulu", Tribe, Modern, -28.5, 31.0),
    e!(Africa: "Xhosa", Tribe, EarlyModern, -32.0, 27.0),
    e!(Africa: "Maasai", Tribe, EarlyModern, -3.0, 36.5),
    e!(Africa: "San", Tribe, Ancient, -24.0, 21.5),
    e!(Africa: "Himba", Tribe, EarlyModern, -18.0, 13.5),
    e!(Africa: "Yoruba", Tribe, Medieval, 7.4, 4.5),
    e!(Africa: "Igbo", Tribe, Medieval, 6.0, 7.5),
    e!(Africa: "Hausa", Tribe, Medieval, 12.0, 8.0),
    e!(Africa: "Fulani", Tribe, Medieval, 14.0, -10.0),
    e!(Africa: "Dogon", Tribe, Medieval, 14.4, -3.3),
    e!(Africa: "Oromo", Tribe, EarlyModern, 7.5, 39.0),
    // --- City-states ---
    e!(Africa: "Carthage", CityState, Ancient, 36.85, 10.32),
    e!(Africa: "Alexandria", CityState, Classical, 31.20, 29.92),
    e!(Africa: "Timbuktu", CityState, Medieval, 16.77, -3.01),
    e!(Africa: "Great Zimbabwe", CityState, Medieval, -20.27, 30.93),
    e!(Africa: "Kilwa", CityState, Medieval, -8.96, 39.51),
    e!(Africa: "Mogadishu", CityState, Medieval, 2.04, 45.34),
    // --- Kingdoms ---
    e!(Africa: "Kingdom of Kush", Kingdom, Ancient, 16.9, 33.7),
    e!(Africa: "Kingdom of Aksum", Kingdom, Classical, 14.13, 38.72),
    e!(Africa: "Kingdom of Kongo", Kingdom, EarlyModern, -6.27, 14.25),
    e!(Africa: "Zulu Kingdom", Kingdom, Modern, -28.3, 31.4),
    e!(Africa: "Kingdom of Dahomey", Kingdom, EarlyModern, 7.18, 2.05),
    e!(Africa: "Buganda", Kingdom, EarlyModern, 0.35, 32.6),
    e!(Africa: "Kingdom of Mutapa", Kingdom, EarlyModern, -17.0, 31.5),
    e!(Africa: "Numidia", Kingdom, Classical, 36.3, 6.6),
    e!(Africa: "Mamluk Sultanate", Kingdom, Medieval, 30.05, 31.24),
    // --- Empires ---
    e!(Africa: "Ancient Egypt", Empire, Ancient, 25.7, 32.65),
    e!(Africa: "Mali Empire", Empire, Medieval, 13.9, -8.0),
    e!(Africa: "Songhai Empire", Empire, EarlyModern, 16.27, -0.05),
    e!(Africa: "Ghana Empire", Empire, Medieval, 15.77, -7.97),
    e!(Africa: "Ethiopian Empire", Empire, Medieval, 9.03, 38.74),
    e!(Africa: "Benin Empire", Empire, EarlyModern, 6.34, 5.62),
    e!(Africa: "Sokoto Caliphate", Empire, Modern, 13.06, 5.24),
    e!(Africa: "Ashanti Empire", Empire, EarlyModern, 6.70, -1.62),
    e!(Africa: "Kanem-Bornu Empire", Empire, Medieval, 13.0, 14.5),
    e!(Africa: "Almoravid Dynasty", Empire, Medieval, 31.6, -8.0),
    // --- Phase A tribes: West Africa ---
    e!(Africa: "Wolof", Tribe, Medieval, 14.7, -16.0),
    e!(Africa: "Serer", Tribe, Medieval, 14.0, -16.3),
    e!(Africa: "Mandinka", Tribe, Medieval, 12.8, -10.8),
    e!(Africa: "Soninke", Tribe, Medieval, 15.0, -9.5),
    e!(Africa: "Bambara", Tribe, EarlyModern, 13.0, -7.5),
    e!(Africa: "Songhai", Tribe, Medieval, 16.0, 0.5),
    e!(Africa: "Mossi", Tribe, Medieval, 12.4, -1.5),
    e!(Africa: "Kanuri", Tribe, Medieval, 12.5, 13.0),
    e!(Africa: "Tiv", Tribe, EarlyModern, 7.3, 9.0),
    e!(Africa: "Nupe", Tribe, EarlyModern, 9.0, 6.0),
    e!(Africa: "Edo", Tribe, Medieval, 6.3, 5.6),
    e!(Africa: "Fon", Tribe, EarlyModern, 7.0, 2.0),
    e!(Africa: "Ewe", Tribe, EarlyModern, 6.5, 0.5),
    e!(Africa: "Akan", Tribe, Medieval, 6.5, -1.5),
    e!(Africa: "Temne", Tribe, EarlyModern, 8.8, -12.5),
    e!(Africa: "Mende", Tribe, EarlyModern, 8.0, -11.5),
    e!(Africa: "Kru", Tribe, EarlyModern, 5.5, -8.0),
    e!(Africa: "Senufo", Tribe, EarlyModern, 10.0, -6.0),
    // --- Phase A tribes: Central Africa ---
    e!(Africa: "Bakongo", Tribe, EarlyModern, -5.5, 14.0),
    e!(Africa: "Luba", Tribe, EarlyModern, -8.0, 25.0),
    e!(Africa: "Lunda", Tribe, EarlyModern, -10.0, 23.5),
    e!(Africa: "Chokwe", Tribe, EarlyModern, -10.5, 20.0),
    e!(Africa: "Mongo", Tribe, EarlyModern, -1.5, 20.0),
    e!(Africa: "Fang", Tribe, EarlyModern, 1.5, 11.5),
    e!(Africa: "Teke", Tribe, EarlyModern, -3.0, 15.5),
    e!(Africa: "Azande", Tribe, EarlyModern, 4.5, 27.5),
    e!(Africa: "Mangbetu", Tribe, EarlyModern, 2.5, 28.0),
    e!(Africa: "Sara", Tribe, EarlyModern, 9.0, 18.0),
    // --- Phase A tribes: East Africa ---
    e!(Africa: "Kikuyu", Tribe, EarlyModern, -0.7, 37.0),
    e!(Africa: "Luo", Tribe, EarlyModern, -0.2, 34.5),
    e!(Africa: "Kamba", Tribe, EarlyModern, -1.5, 38.0),
    e!(Africa: "Chagga", Tribe, EarlyModern, -3.2, 37.4),
    e!(Africa: "Sukuma", Tribe, EarlyModern, -3.0, 33.0),
    e!(Africa: "Nyamwezi", Tribe, EarlyModern, -5.0, 33.0),
    e!(Africa: "Hehe", Tribe, Modern, -8.0, 35.5),
    e!(Africa: "Makonde", Tribe, EarlyModern, -11.0, 39.5),
    e!(Africa: "Yao", Tribe, EarlyModern, -13.5, 35.5),
    e!(Africa: "Chewa", Tribe, EarlyModern, -13.5, 33.5),
    e!(Africa: "Baganda", Tribe, EarlyModern, 0.35, 32.5),
    e!(Africa: "Bemba", Tribe, EarlyModern, -10.5, 31.0),
    e!(Africa: "Dinka", Tribe, EarlyModern, 8.0, 29.5),
    e!(Africa: "Nuer", Tribe, EarlyModern, 8.5, 32.0),
    e!(Africa: "Shilluk", Tribe, EarlyModern, 10.0, 32.0),
    e!(Africa: "Afar", Tribe, Medieval, 11.8, 41.5),
    e!(Africa: "Tigray", Tribe, Medieval, 13.8, 39.0),
    e!(Africa: "Amhara", Tribe, Medieval, 11.5, 38.0),
    e!(Africa: "Sidama", Tribe, EarlyModern, 6.7, 38.4),
    e!(Africa: "Beja", Tribe, Medieval, 18.5, 36.0),
    // --- Phase A tribes: Southern Africa & Madagascar ---
    e!(Africa: "Shona", Tribe, Medieval, -18.0, 31.0),
    e!(Africa: "Ndebele", Tribe, Modern, -20.0, 28.9),
    e!(Africa: "Tswana", Tribe, EarlyModern, -24.0, 25.5),
    e!(Africa: "Sotho", Tribe, Modern, -29.5, 28.0),
    e!(Africa: "Swazi", Tribe, Modern, -26.5, 31.5),
    e!(Africa: "Tsonga", Tribe, EarlyModern, -23.5, 32.0),
    e!(Africa: "Herero", Tribe, EarlyModern, -21.0, 16.5),
    e!(Africa: "Ovambo", Tribe, EarlyModern, -17.8, 15.7),
    e!(Africa: "Nama", Tribe, EarlyModern, -26.0, 17.5),
    e!(Africa: "Khoikhoi", Tribe, EarlyModern, -33.0, 19.5),
    e!(Africa: "Merina", Tribe, EarlyModern, -18.9, 47.5),
    e!(Africa: "Sakalava", Tribe, EarlyModern, -16.5, 45.5),
    // --- Phase A tribes: North Africa & Sahara ---
    e!(Africa: "Kabyle", Tribe, Medieval, 36.6, 4.3),
    e!(Africa: "Riffians", Tribe, Medieval, 35.2, -4.0),
    e!(Africa: "Sanhaja", Tribe, Medieval, 23.0, -10.0),
    e!(Africa: "Zenata", Tribe, Medieval, 33.5, 1.0),
    e!(Africa: "Garamantes", Tribe, Classical, 26.5, 13.0),
    e!(Africa: "Blemmyes", Tribe, Classical, 22.5, 34.5),
    // --- Phase C city-states ---
    e!(Africa: "Cyrene", CityState, Classical, 32.82, 21.86),
    e!(Africa: "Leptis Magna", CityState, Classical, 32.64, 14.29),
    e!(Africa: "Adulis", CityState, Classical, 15.26, 39.66),
    e!(Africa: "Djenne", CityState, Medieval, 13.9, -4.55),
    e!(Africa: "Oualata", CityState, Medieval, 17.3, -7.03),
    e!(Africa: "Kano", CityState, Medieval, 12.0, 8.52),
    e!(Africa: "Ife", CityState, Medieval, 7.47, 4.57),
    e!(Africa: "Zanzibar", CityState, EarlyModern, -6.16, 39.19),
    e!(Africa: "Mombasa", CityState, Medieval, -4.04, 39.67),
    e!(Africa: "Sofala", CityState, Medieval, -20.15, 34.74),
    e!(Africa: "Lamu", CityState, Medieval, -2.27, 40.9),
    e!(Africa: "Sijilmasa", CityState, Medieval, 31.28, -4.28),
    e!(Africa: "Ghadames", CityState, Medieval, 30.13, 9.5),
    e!(Africa: "Tangier", CityState, Medieval, 35.78, -5.81),
    e!(Africa: "Fez", CityState, Medieval, 34.03, -5.0),
    // --- Phase D kingdoms & empires ---
    e!(Africa: "Oyo Empire", Empire, EarlyModern, 8.5, 4.0),
    e!(Africa: "Adal Sultanate", Kingdom, EarlyModern, 9.6, 41.85),
    e!(Africa: "Ajuran Sultanate", Kingdom, Medieval, 2.8, 45.5),
    e!(Africa: "Almohad Caliphate", Empire, Medieval, 31.63, -7.99),
    e!(Africa: "Fatimid Caliphate", Empire, Medieval, 30.04, 31.26),
    e!(Africa: "Wassoulou Empire", Empire, Modern, 11.5, -8.0),
    e!(Africa: "Rozvi Empire", Empire, EarlyModern, -19.5, 29.5),
    e!(Africa: "Kingdom of Loango", Kingdom, EarlyModern, -4.6, 11.8),
    e!(Africa: "Kingdom of Ndongo", Kingdom, EarlyModern, -9.3, 14.9),
    e!(Africa: "Funj Sultanate", Kingdom, EarlyModern, 13.15, 33.93),
    // --- Deep pass: Nile valley & Horn ---
    e!(Africa: "Kingdom of Makuria", Kingdom, Medieval, 18.5, 31.8),
    e!(Africa: "Alodia", Kingdom, Medieval, 15.4, 32.6),
    e!(Africa: "Kingdom of Kerma", Kingdom, Ancient, 19.6, 30.4),
    e!(Africa: "Kingdom of Punt", Kingdom, Ancient, 11.5, 42.5),
    e!(Africa: "Hyksos", Tribe, Ancient, 30.8, 31.8),
];
