//! Americas geo entities. Coordinates are approximate historical heartlands.

use super::{GeoEntity, geo_entity as e};

pub static AMERICAS: &[GeoEntity] = &[
    // --- Countries (modern) ---
    e!(Americas: "United States", Country, Modern, 39.8, -98.5, "us"),
    e!(Americas: "Canada", Country, Modern, 52.9, -97.0, "ca"),
    e!(Americas: "Mexico", Country, Modern, 23.6, -102.5, "mx"),
    e!(Americas: "Guatemala", Country, Modern, 15.5, -90.4, "gt"),
    e!(Americas: "Belize", Country, Modern, 17.2, -88.7, "bz"),
    e!(Americas: "Honduras", Country, Modern, 14.8, -86.6, "hn"),
    e!(Americas: "El Salvador", Country, Modern, 13.8, -88.9, "sv"),
    e!(Americas: "Nicaragua", Country, Modern, 12.9, -85.2, "ni"),
    e!(Americas: "Costa Rica", Country, Modern, 9.9, -84.1, "cr"),
    e!(Americas: "Panama", Country, Modern, 8.5, -80.1, "pa"),
    e!(Americas: "Cuba", Country, Modern, 21.5, -79.5, "cu"),
    e!(Americas: "Jamaica", Country, Modern, 18.1, -77.3, "jm"),
    e!(Americas: "Haiti", Country, Modern, 18.9, -72.7, "ht"),
    e!(Americas: "Dominican Republic", Country, Modern, 18.9, -70.5, "do"),
    e!(Americas: "Puerto Rico", Country, Modern, 18.2, -66.4, "pr"),
    e!(Americas: "Colombia", Country, Modern, 4.6, -74.1, "co"),
    e!(Americas: "Venezuela", Country, Modern, 8.0, -66.0, "ve"),
    e!(Americas: "Guyana", Country, Modern, 5.0, -58.9, "gy"),
    e!(Americas: "Suriname", Country, Modern, 4.1, -56.0, "sr"),
    e!(Americas: "French Guiana", Country, Modern, 4.0, -53.0, "gf"),
    e!(Americas: "Ecuador", Country, Modern, -1.5, -78.5, "ec"),
    e!(Americas: "Peru", Country, Modern, -9.2, -75.0, "pe"),
    e!(Americas: "Bolivia", Country, Modern, -16.5, -64.7, "bo"),
    e!(Americas: "Brazil", Country, Modern, -10.0, -52.0, "br"),
    e!(Americas: "Paraguay", Country, Modern, -23.4, -58.4, "py"),
    e!(Americas: "Uruguay", Country, Modern, -32.8, -56.0, "uy"),
    e!(Americas: "Chile", Country, Modern, -33.45, -70.66, "cl"),
    e!(Americas: "Argentina", Country, Modern, -34.6, -64.0, "ar"),
    e!(Americas: "Greenland", Country, Modern, 72.0, -40.0, "gl"),
    // --- Tribes & peoples ---
    e!(Americas: "Inuit", Tribe, Medieval, 69.0, -95.0),
    e!(Americas: "Cree", Tribe, EarlyModern, 54.0, -100.0),
    e!(Americas: "Haida", Tribe, EarlyModern, 53.0, -132.0),
    e!(Americas: "Iroquois", Tribe, EarlyModern, 43.0, -76.5),
    e!(Americas: "Cherokee", Tribe, EarlyModern, 35.5, -83.5),
    e!(Americas: "Seminole", Tribe, Modern, 27.5, -81.4),
    e!(Americas: "Shawnee", Tribe, EarlyModern, 39.5, -83.0),
    e!(Americas: "Sioux", Tribe, EarlyModern, 44.5, -100.5),
    e!(Americas: "Cheyenne", Tribe, EarlyModern, 41.0, -104.0),
    e!(Americas: "Comanche", Tribe, EarlyModern, 32.5, -99.5),
    e!(Americas: "Apache", Tribe, EarlyModern, 33.5, -108.0),
    e!(Americas: "Navajo", Tribe, EarlyModern, 36.0, -109.5),
    e!(Americas: "Pueblo", Tribe, Medieval, 35.7, -106.0),
    e!(Americas: "Nez Perce", Tribe, EarlyModern, 46.0, -116.5),
    e!(Americas: "Blackfoot", Tribe, EarlyModern, 50.0, -113.0),
    e!(Americas: "Ojibwe", Tribe, EarlyModern, 47.5, -90.0),
    e!(Americas: "Powhatan", Tribe, EarlyModern, 37.5, -76.8),
    e!(Americas: "Taino", Tribe, Medieval, 19.0, -70.7),
    e!(Americas: "Carib", Tribe, Medieval, 15.4, -61.3),
    e!(Americas: "Olmecs", Tribe, Ancient, 18.0, -94.5),
    e!(Americas: "Zapotec", Tribe, Classical, 17.05, -96.72),
    e!(Americas: "Mixtec", Tribe, Medieval, 17.3, -97.7),
    e!(Americas: "Toltec", Tribe, Medieval, 20.06, -99.34),
    e!(Americas: "Maya", Tribe, Classical, 16.75, -89.5),
    e!(Americas: "Mapuche", Tribe, EarlyModern, -38.7, -72.6),
    e!(Americas: "Guarani", Tribe, Medieval, -25.5, -56.5),
    e!(Americas: "Tupi", Tribe, EarlyModern, -13.0, -38.5),
    e!(Americas: "Aymara", Tribe, Medieval, -16.5, -68.5),
    e!(Americas: "Yanomami", Tribe, EarlyModern, 2.5, -63.5),
    // --- City-states ---
    e!(Americas: "Tenochtitlan", CityState, Medieval, 19.43, -99.13),
    e!(Americas: "Teotihuacan", CityState, Classical, 19.69, -98.84),
    e!(Americas: "Tikal", CityState, Classical, 17.22, -89.62),
    e!(Americas: "Chichen Itza", CityState, Medieval, 20.68, -88.57),
    e!(Americas: "Palenque", CityState, Classical, 17.48, -92.05),
    e!(Americas: "Copan", CityState, Classical, 14.84, -89.14),
    e!(Americas: "Cahokia", CityState, Medieval, 38.66, -90.06),
    e!(Americas: "Cusco", CityState, Medieval, -13.53, -71.97),
    // --- Kingdoms ---
    e!(Americas: "Muisca Confederation", Kingdom, Medieval, 5.0, -73.9),
    e!(Americas: "Kingdom of Chimor", Kingdom, Medieval, -8.10, -79.07),
    e!(Americas: "Tiwanaku", Kingdom, Classical, -16.55, -68.67),
    // --- Empires ---
    e!(Americas: "Aztec Empire", Empire, EarlyModern, 19.43, -99.12),
    e!(Americas: "Inca Empire", Empire, EarlyModern, -13.52, -71.97),
    e!(Americas: "Wari Empire", Empire, Medieval, -13.0, -74.0),
    e!(Americas: "Purepecha Empire", Empire, EarlyModern, 19.6, -101.6),
    // --- Phase A tribes: North America ---
    e!(Americas: "Pawnee", Tribe, EarlyModern, 41.5, -98.5),
    e!(Americas: "Crow", Tribe, EarlyModern, 45.5, -108.0),
    e!(Americas: "Hopi", Tribe, Medieval, 35.9, -110.6),
    e!(Americas: "Zuni", Tribe, Medieval, 35.1, -108.8),
    e!(Americas: "Choctaw", Tribe, EarlyModern, 32.5, -89.0),
    e!(Americas: "Muscogee", Tribe, EarlyModern, 32.8, -84.5),
    e!(Americas: "Chickasaw", Tribe, EarlyModern, 34.5, -89.0),
    e!(Americas: "Osage", Tribe, EarlyModern, 37.0, -95.5),
    e!(Americas: "Kiowa", Tribe, EarlyModern, 35.5, -98.5),
    e!(Americas: "Ute", Tribe, EarlyModern, 39.5, -110.0),
    e!(Americas: "Shoshone", Tribe, EarlyModern, 43.0, -114.0),
    e!(Americas: "Paiute", Tribe, EarlyModern, 38.0, -118.5),
    e!(Americas: "Salish", Tribe, EarlyModern, 48.0, -122.5),
    e!(Americas: "Tlingit", Tribe, EarlyModern, 58.3, -134.5),
    e!(Americas: "Tsimshian", Tribe, EarlyModern, 54.5, -128.5),
    e!(Americas: "Chinook", Tribe, EarlyModern, 46.2, -123.5),
    e!(Americas: "Huron", Tribe, EarlyModern, 44.5, -79.5),
    e!(Americas: "Mohicans", Tribe, EarlyModern, 42.8, -73.7),
    e!(Americas: "Lenape", Tribe, EarlyModern, 40.0, -75.0),
    e!(Americas: "Abenaki", Tribe, EarlyModern, 44.5, -71.5),
    e!(Americas: "Beothuk", Tribe, EarlyModern, 48.9, -56.0),
    e!(Americas: "Aleut", Tribe, EarlyModern, 53.5, -167.0),
    e!(Americas: "Yupik", Tribe, EarlyModern, 61.5, -163.5),
    e!(Americas: "Dene", Tribe, EarlyModern, 62.0, -115.0),
    // --- Phase A tribes: Mesoamerica & Caribbean ---
    e!(Americas: "Totonac", Tribe, Classical, 20.0, -97.3),
    e!(Americas: "Huastec", Tribe, Medieval, 22.0, -98.8),
    e!(Americas: "Otomi", Tribe, Medieval, 20.0, -99.5),
    e!(Americas: "Tlaxcaltec", Tribe, EarlyModern, 19.3, -98.2),
    e!(Americas: "Chichimeca", Tribe, Medieval, 22.5, -101.5),
    e!(Americas: "Tarahumara", Tribe, EarlyModern, 27.5, -107.5),
    e!(Americas: "Seri", Tribe, EarlyModern, 29.0, -112.0),
    e!(Americas: "Pipil", Tribe, Medieval, 13.7, -89.2),
    e!(Americas: "Lenca", Tribe, Medieval, 14.5, -88.0),
    e!(Americas: "Miskito", Tribe, EarlyModern, 14.0, -83.5),
    // --- Phase A tribes: South America ---
    e!(Americas: "Wayuu", Tribe, EarlyModern, 11.7, -72.0),
    e!(Americas: "Kuna", Tribe, EarlyModern, 9.3, -78.5),
    e!(Americas: "Shuar", Tribe, EarlyModern, -2.8, -78.0),
    e!(Americas: "Canari", Tribe, Medieval, -2.9, -79.0),
    e!(Americas: "Chachapoya", Tribe, Medieval, -6.2, -77.9),
    e!(Americas: "Shipibo", Tribe, EarlyModern, -8.4, -74.6),
    e!(Americas: "Ashaninka", Tribe, EarlyModern, -11.0, -74.0),
    e!(Americas: "Warao", Tribe, EarlyModern, 9.0, -61.5),
    e!(Americas: "Tikuna", Tribe, EarlyModern, -4.0, -70.0),
    e!(Americas: "Bororo", Tribe, EarlyModern, -16.0, -55.0),
    e!(Americas: "Kayapo", Tribe, EarlyModern, -7.5, -52.0),
    e!(Americas: "Xavante", Tribe, EarlyModern, -14.5, -52.5),
    e!(Americas: "Charrua", Tribe, EarlyModern, -33.0, -56.5),
    e!(Americas: "Tehuelche", Tribe, EarlyModern, -46.0, -70.0),
    e!(Americas: "Selknam", Tribe, EarlyModern, -53.5, -69.0),
    e!(Americas: "Yaghan", Tribe, EarlyModern, -55.0, -68.0),
    e!(Americas: "Diaguita", Tribe, Medieval, -27.0, -66.5),
    e!(Americas: "Guaycuru", Tribe, EarlyModern, -24.5, -59.0),
    e!(Americas: "Huarpe", Tribe, EarlyModern, -32.5, -68.5),
    e!(Americas: "Puelche", Tribe, EarlyModern, -38.0, -65.0),
    // --- Phase B nations ---
    e!(Americas: "Moche", Kingdom, Classical, -8.1, -79.0),
    e!(Americas: "Nazca", Kingdom, Classical, -14.8, -74.9),
    e!(Americas: "Chavin", Kingdom, Ancient, -9.6, -77.2),
    e!(Americas: "Paracas", Kingdom, Classical, -13.8, -76.2),
    e!(Americas: "Tairona", Kingdom, Medieval, 11.0, -73.9),
    e!(Americas: "Viceroyalty of Peru", Country, EarlyModern, -12.05, -77.04),
    e!(Americas: "Viceroyalty of New Granada", Country, EarlyModern, 4.65, -74.05),
    e!(Americas: "Viceroyalty of Rio de la Plata", Country, EarlyModern, -34.6, -58.38),
    e!(Americas: "Gran Colombia", Country, Modern, 7.1, -70.0),
    e!(Americas: "Palmares", Kingdom, EarlyModern, -9.4, -36.2),
    e!(Americas: "Wabanaki Confederacy", Kingdom, EarlyModern, 45.0, -69.0),
    e!(Americas: "Comancheria", Kingdom, Modern, 33.5, -100.5),
    e!(Americas: "Three Fires Confederacy", Kingdom, EarlyModern, 45.5, -84.0),
    e!(Americas: "New France", Country, EarlyModern, 46.8, -71.2),
    e!(Americas: "New Spain", Country, EarlyModern, 19.45, -99.05),
    e!(Americas: "Thirteen Colonies", Country, EarlyModern, 39.9, -75.2),
    e!(Americas: "Republic of Texas", Country, Modern, 30.3, -97.7),
    e!(Americas: "California Republic", Country, Modern, 38.3, -122.5),
    e!(Americas: "Ruperts Land", Country, EarlyModern, 55.0, -95.0),
    // --- Phase C city-states ---
    e!(Americas: "Mayapan", CityState, Medieval, 20.63, -89.46),
    e!(Americas: "Calakmul", CityState, Classical, 18.1, -89.81),
    e!(Americas: "El Tajin", CityState, Classical, 20.45, -97.38),
    e!(Americas: "Monte Alban", CityState, Classical, 17.04, -96.77),
    e!(Americas: "Cholula", CityState, Classical, 19.06, -98.3),
    e!(Americas: "Uxmal", CityState, Medieval, 20.36, -89.77),
    e!(Americas: "Pachacamac", CityState, Medieval, -12.26, -76.9),
    e!(Americas: "Moundville", CityState, Medieval, 33.0, -87.6),
    e!(Americas: "Etowah", CityState, Medieval, 34.1, -84.8),
    e!(Americas: "Taos Pueblo", CityState, Medieval, 36.4, -105.6),
    e!(Americas: "Vinland", CityState, Medieval, 51.5, -55.5),
    // --- Deep pass: South America tribes & peoples ---
    e!(Americas: "Quechua", Tribe, Medieval, -14.2, -72.5),
    e!(Americas: "Chono", Tribe, EarlyModern, -45.0, -74.0),
    e!(Americas: "Kawesqar", Tribe, EarlyModern, -50.0, -74.5),
    e!(Americas: "Wichi", Tribe, EarlyModern, -23.5, -63.0),
    e!(Americas: "Toba", Tribe, EarlyModern, -26.5, -60.0),
    e!(Americas: "Ache", Tribe, EarlyModern, -25.5, -55.5),
    e!(Americas: "Chiquitano", Tribe, EarlyModern, -17.5, -61.5),
    e!(Americas: "Guajajara", Tribe, EarlyModern, -4.5, -45.5),
    e!(Americas: "Munduruku", Tribe, EarlyModern, -7.0, -58.0),
    e!(Americas: "Huaorani", Tribe, EarlyModern, -1.0, -77.0),
    e!(Americas: "Embera", Tribe, EarlyModern, 7.0, -76.5),
    e!(Americas: "Timoto-Cuica", Tribe, Medieval, 8.6, -71.0),
    e!(Americas: "Chanka", Tribe, Medieval, -13.7, -73.4),
    e!(Americas: "Colla", Tribe, Medieval, -15.8, -70.0),
    // --- Deep pass: South America states & cities ---
    e!(Americas: "Sican", Kingdom, Medieval, -6.5, -79.8),
    e!(Americas: "Chincha", Kingdom, Medieval, -13.4, -76.1),
    e!(Americas: "Captaincy General of Chile", Country, EarlyModern, -33.44, -70.65),
    e!(Americas: "Portuguese Brazil", Country, EarlyModern, -12.97, -38.5),
    e!(Americas: "Empire of Brazil", Empire, Modern, -22.9, -43.2),
    e!(Americas: "Cartagena", CityState, EarlyModern, 10.42, -75.53),
    e!(Americas: "Potosi", CityState, EarlyModern, -19.58, -65.75),
    e!(Americas: "Ouro Preto", CityState, EarlyModern, -20.39, -43.5),
    e!(Americas: "Havana", CityState, EarlyModern, 23.14, -82.36),
    e!(Americas: "Port Royal", CityState, EarlyModern, 17.94, -76.84),
    e!(Americas: "Tortuga", CityState, EarlyModern, 20.06, -72.79),
    // --- Deep pass: North America states ---
    e!(Americas: "Calusa", Kingdom, Medieval, 26.5, -81.9),
    e!(Americas: "Cofitachequi", Kingdom, EarlyModern, 34.2, -80.9),
    e!(Americas: "New Netherland", Country, EarlyModern, 40.71, -74.0),
    e!(Americas: "New Sweden", Country, EarlyModern, 39.7, -75.5),
    e!(Americas: "Vermont Republic", Country, Modern, 44.26, -72.58),
    e!(Americas: "Deseret", Country, Modern, 40.76, -111.89),
    e!(Americas: "First Mexican Empire", Empire, Modern, 19.4, -99.15),
    e!(Americas: "Federal Republic of Central America", Country, Modern, 14.6, -90.5),
    e!(Americas: "Santa Fe", CityState, EarlyModern, 35.69, -105.94),
];
