//! European geo entities. Coordinates are approximate historical heartlands.

use super::{geo_entity as e, GeoEntity};

pub static EUROPE: &[GeoEntity] = &[
    // --- Countries (modern) ---
    e!(Europe: "Iceland", Country, Modern, 65.0, -18.5, "is"),
    e!(Europe: "Ireland", Country, Modern, 53.2, -7.7, "ie"),
    e!(Europe: "United Kingdom", Country, Modern, 54.0, -2.5, "gb"),
    e!(Europe: "Portugal", Country, Modern, 39.6, -8.0, "pt"),
    e!(Europe: "Spain", Country, Modern, 40.2, -3.6, "es"),
    e!(Europe: "France", Country, Modern, 46.6, 2.5, "fr"),
    e!(Europe: "Belgium", Country, Modern, 50.6, 4.6, "be"),
    e!(Europe: "Netherlands", Country, Modern, 52.2, 5.5, "nl"),
    e!(Europe: "Luxembourg", Country, Modern, 49.8, 6.1, "lu"),
    e!(Europe: "Germany", Country, Modern, 51.1, 10.4, "de"),
    e!(Europe: "Switzerland", Country, Modern, 46.8, 8.2, "ch"),
    e!(Europe: "Austria", Country, Modern, 47.6, 14.1, "at"),
    e!(Europe: "Italy", Country, Modern, 42.8, 12.5, "it"),
    e!(Europe: "Norway", Country, Modern, 61.0, 9.0, "no"),
    e!(Europe: "Sweden", Country, Modern, 62.0, 15.0, "se"),
    e!(Europe: "Finland", Country, Modern, 64.0, 26.0, "fi"),
    e!(Europe: "Denmark", Country, Modern, 56.0, 9.5, "dk"),
    e!(Europe: "Poland", Country, Modern, 52.1, 19.4, "pl"),
    e!(Europe: "Czechia", Country, Modern, 49.8, 15.5, "cz"),
    e!(Europe: "Slovakia", Country, Modern, 48.7, 19.5, "sk"),
    e!(Europe: "Hungary", Country, Modern, 47.2, 19.4, "hu"),
    e!(Europe: "Romania", Country, Modern, 45.9, 25.0, "ro"),
    e!(Europe: "Bulgaria", Country, Modern, 42.7, 25.2, "bg"),
    e!(Europe: "Greece", Country, Modern, 39.0, 22.0, "gr"),
    e!(Europe: "Serbia", Country, Modern, 44.2, 20.9, "rs"),
    e!(Europe: "Croatia", Country, Modern, 45.5, 16.0, "hr"),
    e!(Europe: "Bosnia and Herzegovina", Country, Modern, 44.2, 17.8, "ba"),
    e!(Europe: "Slovenia", Country, Modern, 46.1, 14.8, "si"),
    e!(Europe: "North Macedonia", Country, Modern, 41.6, 21.7, "mk"),
    e!(Europe: "Albania", Country, Modern, 41.1, 20.1, "al"),
    e!(Europe: "Ukraine", Country, Modern, 49.0, 31.4, "ua"),
    e!(Europe: "Belarus", Country, Modern, 53.5, 28.0, "by"),
    e!(Europe: "Moldova", Country, Modern, 47.2, 28.5, "md"),
    e!(Europe: "Lithuania", Country, Modern, 55.2, 23.9, "lt"),
    e!(Europe: "Latvia", Country, Modern, 56.9, 24.9, "lv"),
    e!(Europe: "Estonia", Country, Modern, 58.7, 25.5, "ee"),
    e!(Europe: "Russia", Country, Modern, 55.7, 37.6, "ru"),
    e!(Europe: "Monaco", Country, Modern, 43.73, 7.42, "mc"),
    e!(Europe: "Andorra", Country, Modern, 42.5, 1.5, "ad"),
    e!(Europe: "Malta", Country, Modern, 35.9, 14.4, "mt"),
    e!(Europe: "Cyprus", Country, Modern, 35.0, 33.2, "cy"),
    // --- Tribes & ancient peoples ---
    e!(Europe: "Iceni", Tribe, Ancient, 52.7, 0.9),
    e!(Europe: "Gauls", Tribe, Ancient, 47.0, 2.5),
    e!(Europe: "Celtiberians", Tribe, Ancient, 41.5, -2.5),
    e!(Europe: "Britons", Tribe, Ancient, 52.0, -1.5),
    e!(Europe: "Picts", Tribe, Ancient, 57.0, -4.0),
    e!(Europe: "Gaels", Tribe, Ancient, 53.5, -8.0),
    e!(Europe: "Saxons", Tribe, Classical, 52.5, 9.0),
    e!(Europe: "Angles", Tribe, Classical, 54.5, 9.5),
    e!(Europe: "Jutes", Tribe, Classical, 55.5, 9.0),
    e!(Europe: "Franks", Tribe, Classical, 50.5, 6.5),
    e!(Europe: "Alemanni", Tribe, Classical, 48.5, 9.0),
    e!(Europe: "Suebi", Tribe, Ancient, 52.0, 13.0),
    e!(Europe: "Goths", Tribe, Classical, 51.5, 21.0),
    e!(Europe: "Visigoths", Tribe, Classical, 41.0, -4.0),
    e!(Europe: "Ostrogoths", Tribe, Classical, 45.0, 12.0),
    e!(Europe: "Vandals", Tribe, Classical, 50.5, 17.0),
    e!(Europe: "Burgundians", Tribe, Classical, 47.5, 5.0),
    e!(Europe: "Lombards", Tribe, Medieval, 45.5, 9.5),
    e!(Europe: "Norsemen", Tribe, Medieval, 60.5, 8.0),
    e!(Europe: "Rus", Tribe, Medieval, 58.5, 31.3),
    e!(Europe: "Polans", Tribe, Medieval, 52.4, 17.0),
    e!(Europe: "Magyars", Tribe, Medieval, 47.0, 20.0),
    e!(Europe: "Basques", Tribe, Ancient, 43.0, -2.5),
    e!(Europe: "Etruscans", Tribe, Ancient, 42.5, 11.5),
    e!(Europe: "Latins", Tribe, Ancient, 41.8, 12.6),
    e!(Europe: "Samnites", Tribe, Ancient, 41.5, 14.5),
    e!(Europe: "Dacians", Tribe, Ancient, 45.5, 24.0),
    e!(Europe: "Thracians", Tribe, Ancient, 42.2, 25.5),
    e!(Europe: "Illyrians", Tribe, Ancient, 43.5, 17.5),
    e!(Europe: "Scythians", Tribe, Ancient, 47.0, 34.0),
    e!(Europe: "Sarmatians", Tribe, Classical, 48.0, 40.0),
    e!(Europe: "Huns", Tribe, Classical, 46.8, 19.5),
    e!(Europe: "Helvetii", Tribe, Ancient, 46.8, 7.8),
    e!(Europe: "Boii", Tribe, Ancient, 49.5, 14.5),
    e!(Europe: "Sami", Tribe, Medieval, 68.5, 22.0),
    // --- City-states ---
    e!(Europe: "Athens", CityState, Classical, 37.98, 23.73),
    e!(Europe: "Sparta", CityState, Classical, 37.08, 22.43),
    e!(Europe: "Corinth", CityState, Classical, 37.94, 22.93),
    e!(Europe: "Thebes", CityState, Classical, 38.32, 23.32),
    e!(Europe: "Syracuse", CityState, Classical, 37.07, 15.29),
    e!(Europe: "Venice", CityState, Medieval, 45.44, 12.34),
    e!(Europe: "Genoa", CityState, Medieval, 44.41, 8.93),
    e!(Europe: "Florence", CityState, Medieval, 43.77, 11.26),
    e!(Europe: "Milan", CityState, Medieval, 45.46, 9.19),
    e!(Europe: "Pisa", CityState, Medieval, 43.72, 10.40),
    e!(Europe: "Ragusa", CityState, Medieval, 42.65, 18.09),
    e!(Europe: "Novgorod", CityState, Medieval, 58.52, 31.27),
    e!(Europe: "Lubeck", CityState, Medieval, 53.87, 10.69),
    // --- Kingdoms ---
    e!(Europe: "Kingdom of Wessex", Kingdom, Medieval, 51.0, -2.0),
    e!(Europe: "Kingdom of Mercia", Kingdom, Medieval, 52.6, -1.5),
    e!(Europe: "Kingdom of Northumbria", Kingdom, Medieval, 55.0, -1.8),
    e!(Europe: "Kingdom of Scotland", Kingdom, Medieval, 56.5, -4.0),
    e!(Europe: "Kingdom of Aragon", Kingdom, Medieval, 41.6, -0.9),
    e!(Europe: "Kingdom of Castile", Kingdom, Medieval, 41.7, -4.0),
    e!(Europe: "Kingdom of Leon", Kingdom, Medieval, 42.6, -5.6),
    e!(Europe: "Kingdom of Navarre", Kingdom, Medieval, 42.8, -1.6),
    e!(Europe: "Kingdom of Bohemia", Kingdom, Medieval, 50.1, 14.4),
    e!(Europe: "Kingdom of Naples", Kingdom, Medieval, 40.85, 14.27),
    e!(Europe: "Kingdom of Sicily", Kingdom, Medieval, 37.6, 14.0),
    e!(Europe: "Grand Duchy of Lithuania", Kingdom, Medieval, 54.7, 25.3),
    e!(Europe: "Duchy of Normandy", Kingdom, Medieval, 49.2, 0.2),
    e!(Europe: "Duchy of Burgundy", Kingdom, Medieval, 47.3, 4.8),
    e!(Europe: "Kievan Rus", Kingdom, Medieval, 50.45, 30.52),
    e!(Europe: "Papal States", Kingdom, Medieval, 42.5, 12.5),
    // --- Empires ---
    e!(Europe: "Roman Empire", Empire, Classical, 41.9, 12.5),
    e!(Europe: "Byzantine Empire", Empire, Medieval, 41.01, 28.97),
    e!(Europe: "Holy Roman Empire", Empire, Medieval, 50.0, 9.0),
    e!(Europe: "Carolingian Empire", Empire, Medieval, 50.77, 6.08),
    e!(Europe: "Austro-Hungarian Empire", Empire, Modern, 48.2, 16.4),
    e!(Europe: "Russian Empire", Empire, EarlyModern, 59.94, 30.31),
    e!(Europe: "First French Empire", Empire, Modern, 48.86, 2.35),
    // --- Phase A tribes: Gaulish ---
    e!(Europe: "Arverni", Tribe, Ancient, 45.7, 3.1),
    e!(Europe: "Aedui", Tribe, Ancient, 46.95, 4.3),
    e!(Europe: "Sequani", Tribe, Ancient, 47.25, 6.0),
    e!(Europe: "Parisii", Tribe, Ancient, 48.85, 2.35),
    e!(Europe: "Remi", Tribe, Ancient, 49.25, 4.03),
    e!(Europe: "Treveri", Tribe, Ancient, 49.75, 6.65),
    e!(Europe: "Veneti", Tribe, Ancient, 47.66, -2.76),
    e!(Europe: "Bituriges", Tribe, Ancient, 47.08, 2.4),
    e!(Europe: "Carnutes", Tribe, Ancient, 48.45, 1.5),
    e!(Europe: "Senones", Tribe, Ancient, 48.2, 3.28),
    e!(Europe: "Allobroges", Tribe, Ancient, 45.6, 5.9),
    e!(Europe: "Aquitani", Tribe, Ancient, 44.2, -0.6),
    e!(Europe: "Belgae", Tribe, Ancient, 50.0, 4.0),
    e!(Europe: "Nervii", Tribe, Ancient, 50.3, 3.9),
    e!(Europe: "Eburones", Tribe, Ancient, 50.8, 5.7),
    e!(Europe: "Menapii", Tribe, Ancient, 51.0, 3.5),
    e!(Europe: "Morini", Tribe, Ancient, 50.7, 1.9),
    e!(Europe: "Atrebates", Tribe, Ancient, 50.3, 2.78),
    e!(Europe: "Pictones", Tribe, Ancient, 46.58, -0.34),
    e!(Europe: "Santones", Tribe, Ancient, 45.75, -0.63),
    e!(Europe: "Cadurci", Tribe, Ancient, 44.45, 1.44),
    e!(Europe: "Volcae", Tribe, Ancient, 43.6, 3.9),
    e!(Europe: "Salluvii", Tribe, Ancient, 43.5, 5.4),
    e!(Europe: "Insubres", Tribe, Ancient, 45.47, 9.0),
    e!(Europe: "Cenomani", Tribe, Ancient, 45.4, 10.2),
    e!(Europe: "Taurini", Tribe, Ancient, 45.07, 7.68),
    // --- Phase A tribes: British & Irish ---
    e!(Europe: "Brigantes", Tribe, Ancient, 54.0, -1.8),
    e!(Europe: "Silures", Tribe, Ancient, 51.7, -3.3),
    e!(Europe: "Ordovices", Tribe, Ancient, 52.8, -3.9),
    e!(Europe: "Trinovantes", Tribe, Ancient, 51.85, 0.6),
    e!(Europe: "Catuvellauni", Tribe, Ancient, 51.85, -0.4),
    e!(Europe: "Cantiaci", Tribe, Ancient, 51.28, 1.08),
    e!(Europe: "Durotriges", Tribe, Ancient, 50.7, -2.4),
    e!(Europe: "Dumnonii", Tribe, Ancient, 50.5, -4.0),
    e!(Europe: "Cornovii", Tribe, Ancient, 52.7, -2.5),
    e!(Europe: "Votadini", Tribe, Ancient, 55.8, -2.5),
    e!(Europe: "Caledonii", Tribe, Ancient, 56.8, -4.2),
    e!(Europe: "Scoti", Tribe, Classical, 55.0, -7.3),
    e!(Europe: "Ulaid", Tribe, Classical, 54.5, -6.5),
    e!(Europe: "Connachta", Tribe, Classical, 53.7, -8.8),
    // --- Phase A tribes: Germanic ---
    e!(Europe: "Cherusci", Tribe, Ancient, 52.3, 9.5),
    e!(Europe: "Chatti", Tribe, Ancient, 51.0, 9.3),
    e!(Europe: "Marcomanni", Tribe, Ancient, 49.5, 13.5),
    e!(Europe: "Quadi", Tribe, Ancient, 48.6, 17.0),
    e!(Europe: "Frisii", Tribe, Ancient, 53.2, 5.8),
    e!(Europe: "Batavi", Tribe, Ancient, 51.9, 5.5),
    e!(Europe: "Chauci", Tribe, Ancient, 53.5, 8.5),
    e!(Europe: "Semnones", Tribe, Ancient, 52.3, 13.8),
    e!(Europe: "Gepids", Tribe, Classical, 46.0, 21.0),
    e!(Europe: "Heruli", Tribe, Classical, 47.8, 17.2),
    e!(Europe: "Rugii", Tribe, Classical, 54.0, 13.5),
    e!(Europe: "Ubii", Tribe, Ancient, 50.94, 6.96),
    e!(Europe: "Sicambri", Tribe, Ancient, 51.2, 7.0),
    e!(Europe: "Cimbri", Tribe, Ancient, 56.8, 9.5),
    e!(Europe: "Teutons", Tribe, Ancient, 56.0, 8.5),
    // --- Phase A tribes: Iberian ---
    e!(Europe: "Lusitanians", Tribe, Ancient, 39.5, -7.9),
    e!(Europe: "Vettones", Tribe, Ancient, 40.5, -5.7),
    e!(Europe: "Vaccaei", Tribe, Ancient, 41.6, -4.7),
    e!(Europe: "Cantabri", Tribe, Ancient, 43.2, -4.0),
    e!(Europe: "Astures", Tribe, Ancient, 43.0, -6.0),
    e!(Europe: "Gallaeci", Tribe, Ancient, 42.9, -8.0),
    e!(Europe: "Turdetani", Tribe, Ancient, 37.5, -5.9),
    e!(Europe: "Ilergetes", Tribe, Ancient, 41.6, 0.6),
    e!(Europe: "Edetani", Tribe, Ancient, 39.5, -0.5),
    e!(Europe: "Bastetani", Tribe, Ancient, 37.5, -2.8),
    // --- Phase A tribes: Italic & Aegean ---
    e!(Europe: "Sabines", Tribe, Ancient, 42.3, 12.9),
    e!(Europe: "Volsci", Tribe, Ancient, 41.5, 13.0),
    e!(Europe: "Umbrians", Tribe, Ancient, 43.1, 12.4),
    e!(Europe: "Ligurians", Tribe, Ancient, 44.3, 8.5),
    e!(Europe: "Picentes", Tribe, Ancient, 43.3, 13.4),
    e!(Europe: "Bruttii", Tribe, Ancient, 39.1, 16.3),
    e!(Europe: "Lucani", Tribe, Ancient, 40.4, 15.8),
    e!(Europe: "Messapii", Tribe, Ancient, 40.4, 18.0),
    e!(Europe: "Sicels", Tribe, Ancient, 37.4, 14.8),
    e!(Europe: "Minoans", Tribe, Ancient, 35.3, 25.0),
    e!(Europe: "Mycenaeans", Tribe, Ancient, 37.73, 22.75),
    // --- Phase A tribes: Balkan & Danubian ---
    e!(Europe: "Getae", Tribe, Ancient, 44.2, 26.5),
    e!(Europe: "Moesi", Tribe, Ancient, 43.7, 23.0),
    e!(Europe: "Triballi", Tribe, Ancient, 43.6, 22.5),
    e!(Europe: "Paeonians", Tribe, Ancient, 41.7, 22.0),
    e!(Europe: "Dardani", Tribe, Ancient, 42.6, 21.1),
    e!(Europe: "Liburni", Tribe, Ancient, 44.5, 15.0),
    e!(Europe: "Delmatae", Tribe, Ancient, 43.8, 16.7),
    e!(Europe: "Pannonians", Tribe, Ancient, 45.5, 18.0),
    e!(Europe: "Iapodes", Tribe, Ancient, 44.9, 15.3),
    e!(Europe: "Bastarnae", Tribe, Classical, 47.5, 27.0),
    e!(Europe: "Carpi", Tribe, Classical, 46.8, 26.5),
    e!(Europe: "Macedonians", Tribe, Classical, 40.85, 22.0),
    // --- Phase A tribes: steppe fringe & east ---
    e!(Europe: "Cumans", Tribe, Medieval, 46.5, 35.0),
    e!(Europe: "Pechenegs", Tribe, Medieval, 46.0, 30.0),
    e!(Europe: "Khazars", Tribe, Medieval, 46.5, 47.0),
    e!(Europe: "Avars", Tribe, Medieval, 46.9, 19.0),
    e!(Europe: "Volga Bulgars", Tribe, Medieval, 55.0, 49.3),
    e!(Europe: "Mordvins", Tribe, Medieval, 54.4, 44.5),
    e!(Europe: "Drevlians", Tribe, Medieval, 51.0, 29.0),
    e!(Europe: "Severians", Tribe, Medieval, 51.5, 33.0),
    // --- Phase A tribes: Baltic, Slavic & Nordic ---
    e!(Europe: "Prussians", Tribe, Medieval, 54.6, 20.5),
    e!(Europe: "Curonians", Tribe, Medieval, 56.5, 21.5),
    e!(Europe: "Samogitians", Tribe, Medieval, 55.7, 22.5),
    e!(Europe: "Livonians", Tribe, Medieval, 57.5, 22.0),
    e!(Europe: "Karelians", Tribe, Medieval, 62.0, 32.0),
    e!(Europe: "Sorbs", Tribe, Medieval, 51.5, 14.3),
    e!(Europe: "Obotrites", Tribe, Medieval, 53.8, 11.5),
    e!(Europe: "Pomeranians", Tribe, Medieval, 54.0, 16.5),
    e!(Europe: "Geats", Tribe, Medieval, 57.7, 13.0),
    e!(Europe: "Svear", Tribe, Medieval, 59.5, 17.5),
    // --- Phase C city-states ---
    e!(Europe: "Massalia", CityState, Classical, 43.3, 5.37),
    e!(Europe: "Byzantion", CityState, Classical, 41.02, 28.95),
    e!(Europe: "Emporion", CityState, Classical, 42.13, 3.12),
    e!(Europe: "Tarentum", CityState, Classical, 40.47, 17.24),
    e!(Europe: "Croton", CityState, Classical, 39.08, 17.13),
    e!(Europe: "Cumae", CityState, Classical, 40.85, 14.05),
    e!(Europe: "Mycenae", CityState, Ancient, 37.73, 22.76),
    e!(Europe: "Knossos", CityState, Ancient, 35.3, 25.16),
    e!(Europe: "Hamburg", CityState, Medieval, 53.55, 10.0),
    e!(Europe: "Bremen", CityState, Medieval, 53.08, 8.8),
    e!(Europe: "Danzig", CityState, Medieval, 54.35, 18.65),
    e!(Europe: "Riga", CityState, Medieval, 56.95, 24.1),
    e!(Europe: "Visby", CityState, Medieval, 57.64, 18.3),
    e!(Europe: "Bruges", CityState, Medieval, 51.21, 3.22),
    e!(Europe: "Antwerp", CityState, EarlyModern, 51.22, 4.4),
    e!(Europe: "Augsburg", CityState, Medieval, 48.37, 10.9),
    e!(Europe: "Nuremberg", CityState, Medieval, 49.45, 11.08),
    e!(Europe: "Bern", CityState, Medieval, 46.95, 7.45),
    e!(Europe: "Geneva", CityState, EarlyModern, 46.2, 6.15),
    e!(Europe: "Amalfi", CityState, Medieval, 40.63, 14.6),
    e!(Europe: "Siena", CityState, Medieval, 43.32, 11.33),
    e!(Europe: "Bologna", CityState, Medieval, 44.49, 11.34),
    e!(Europe: "Pskov", CityState, Medieval, 57.8, 28.3),
    e!(Europe: "Toledo", CityState, Medieval, 39.86, -4.02),
    // --- Phase D kingdoms & empires (era balance) ---
    e!(Europe: "Polish-Lithuanian Commonwealth", Empire, EarlyModern, 52.2, 21.0),
    e!(Europe: "Dutch Republic", Kingdom, EarlyModern, 52.37, 4.9),
    e!(Europe: "Swedish Empire", Empire, EarlyModern, 59.33, 18.07),
    e!(Europe: "Spanish Empire", Empire, EarlyModern, 40.4, -3.7),
    e!(Europe: "Portuguese Empire", Empire, EarlyModern, 38.72, -9.14),
    e!(Europe: "Crimean Khanate", Kingdom, EarlyModern, 44.95, 34.1),
    e!(Europe: "Golden Horde", Empire, Medieval, 46.3, 48.0),
    e!(Europe: "Kingdom of Prussia", Kingdom, EarlyModern, 52.52, 13.4),
    e!(Europe: "Grand Duchy of Moscow", Kingdom, Medieval, 55.76, 37.61),
    e!(Europe: "Odrysian Kingdom", Kingdom, Classical, 42.0, 25.8),
    e!(Europe: "Kingdom of Epirus", Kingdom, Classical, 39.6, 20.8),
    e!(Europe: "Caliphate of Cordoba", Kingdom, Medieval, 37.88, -4.78),
    e!(Europe: "Kingdom of Asturias", Kingdom, Medieval, 43.36, -5.85),
    e!(Europe: "Republic of Novgorod", Kingdom, Medieval, 58.5, 31.3),
    // --- Deep pass: Balkans & eastern Europe ---
    e!(Europe: "Wallachia", Kingdom, Medieval, 44.43, 26.1),
    e!(Europe: "Moldavia", Kingdom, Medieval, 47.2, 27.6),
    e!(Europe: "Transylvania", Kingdom, EarlyModern, 46.77, 23.6),
    e!(Europe: "Serbian Empire", Empire, Medieval, 42.66, 21.17),
    e!(Europe: "First Bulgarian Empire", Empire, Medieval, 43.08, 25.65),
    e!(Europe: "Kingdom of Galicia-Volhynia", Kingdom, Medieval, 49.84, 24.03),
];
