[package]
name = "sow-client-world"
version = "0.1.0"
edition = "2021"
description = "Shadows of War — client simulation, rendering, and UI glue"
license = "AGPL-3.0-or-later"

[features]
default = []
dev = ["sow-ui/dev"]

[dependencies]
sow-audio = { workspace = true }
sow-core = { workspace = true }
sow-data = { workspace = true }
sow-assets = { workspace = true }
sow-assets-ui = { workspace = true }
sow-render = { workspace = true }
blade-graphics = { workspace = true }
sow-ui = { workspace = true }
sow-ui-kit = { workspace = true }
sow-ui-game = { workspace = true }
sow-i18n = { workspace = true }
sow-net = { workspace = true }
log = { workspace = true }
winit = { workspace = true }
egui = { workspace = true }
blade-egui = { workspace = true }
bincode.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
brotli = { workspace = true }
ehttp = { workspace = true, features = ["streaming"] }
crossbeam-channel = { workspace = true }
web-time = { workspace = true }
image = { workspace = true }
url = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { workspace = true }
wasm-bindgen = { workspace = true }
getrandom = { workspace = true, features = ["js"] }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
web-sys = { workspace = true, features = ["Window", "Document", "Element", "HtmlElement", "HtmlInputElement", "HtmlAnchorElement", "HtmlCanvasElement", "Navigator", "CssStyleDeclaration", "Node", "VisibilityState", "Location", "BinaryType", "Worker", "MessageEvent", "Storage", "MediaQueryList", "Blob", "Url", "BlobPropertyBag", "VisualViewport", "Event"] }
js-sys = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = { workspace = true }
open = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }
