sow-database {
    host.hostname = "sow-database.local";
    path = /zroot/jails/sow-database;
    ip4 = inherit;
    ip6 = inherit;
    mount.devfs;
    devfs_ruleset = 4;
    mount.fstab = "/etc/fstab.sow-database";
    exec.clean;
    exec.start = "/bin/sh /etc/rc";
    exec.stop = "/bin/sh /etc/rc.shutdown jail";
    allow.set_hostname = 0;
    allow.sysvipc = 0;
    enforce_statfs = 2;
}
