worker_processes auto;
worker_rlimit_nofile 250000;

events {
    worker_connections 200000;
}

http {
    include /usr/local/etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    server_tokens off;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    include /usr/local/etc/nginx/conf.d/*.conf;
}
