// Spirit animals for tribes — one per tribe name (stable hash) or id fallback.
pub const TRIBE_ANIMALS: [&str; 40] = [
    "🦁", "🐯", "🐆", "🐺", "🦊", "🦝", "🐻", "🐨", "🐼", "🐗", "🦄", "🦅", "🦉", "🐊", "🦖", "🐉",
    "🦈", "🦂", "🐃", "🐏", "🐘", "🦏", "🦍", "🐎", "🦌", "🦇", "🦢", "🦩", "🐍", "🐢", "🐙", "🐬",
    "🐝", "🦋", "🕷️", "🦦", "🦫", "🐫", "🦘", "🦡",
];

pub fn animal_for_name(name: &str) -> &'static str {
    let mut h = 0u32;
    for b in name.bytes() {
        h = h.wrapping_mul(31).wrapping_add(b as u32);
    }
    TRIBE_ANIMALS[h as usize % TRIBE_ANIMALS.len()]
}

pub fn animal_for_id(id: u16) -> &'static str {
    TRIBE_ANIMALS[(id as usize) % TRIBE_ANIMALS.len()]
}

// Auto-generated fallback list of historical tribes and nations
pub const FALLBACK_TRIBES: &[&str] = &[
    "Nalu",
    "Pomo",
    "Qajars",
    "Bahía",
    "Huichol",
    "Yuezhi",
    "Wari",
    "Moche",
    "Perrhaebi",
    "Goguryeo",
    "Emberá",
    "Garhwalis",
    "Fulani",
    "Micmac",
    "Mog",
    "Kpelle",
    "Zands",
    "Pojoaque",
    "Kazakhs",
    "Blemmyae",
    "Tokelauan",
    "Franks",
    "Hotakis",
    "Euganei",
    "Medulli",
    "Dimasa",
    "Huancavilca",
    "Lyncestae",
    "Luritja",
    "Volhynians",
    "Pipil",
    "Qara Khitai",
    "Missouri",
    "Yaqui",
    "Afsharids",
    "Carib",
    "Ojibwe",
    "Goths",
    "Bhils",
    "Ceutrones",
    "Picuris",
    "Hurrians",
    "Kashmiris",
    "Dinka",
    "Maasai",
    "Kipchaks",
    "Dogras",
    "Akkadians",
    "Huastec",
    "Micronesians",
    "Tigre",
    "Tesuque",
    "Vyatichs",
    "Rendille",
    "Garo",
    "Jomon",
    "Kolis",
    "Chakma",
    "Ixil",
    "Kyrgyz",
    "Tymphaei",
    "Kotwalia",
    "Antes",
    "Maldhari",
    "Solomon Islanders",
    "Tzutuil",
    "Kanjobal",
    "Salassi",
    "Masalit",
    "Dacians",
    "Aborigines",
    "Fenni",
    "Chaonians",
    "Mixtec",
    "Crobyzi",
    "Zia",
    "Khassonke",
    "Aesti",
    "Pashtuns",
    "Muvians",
    "Lepontii",
    "Britons",
    "Boran",
    "Chamorro",
    "Zaghawa",
    "Gujjar",
    "Igbo",
    "Panotii",
    "Kissi",
    "Alyawarre",
    "Tatars",
    "Lapiths",
    "Bhutias",
    "Buglé",
    "Lydians",
    "Venethi",
    "Cañari",
    "Carians",
    "San",
    "Ahir",
    "Kato",
    "Gola",
    "Coast Miwok",
    "Nunga",
    "Orestae",
    "Rotumans",
    "Noanamá",
    "Rugii",
    "Huns",
    "Yuki",
    "Karankawa",
    "Bakongo",
    "Frisians",
    "Wolof",
    "Wiyot",
    "Afar",
    "Sitones",
    "Eastern Arrernte",
    "Cassopaeans",
    "Vasava",
    "Warlis",
    "Canarians",
    "Quimbaya",
    "Uyghurs",
    "Ilkhanids",
    "Blue Horde",
    "Laguna",
    "Tzotzil",
    "Bullom",
    "Kuki",
    "Iowa",
    "Dregovichs",
    "Dalmatiae",
    "Guanches",
    "Sithones",
    "Cynocephali",
    "Atsugewi",
    "Massagetae",
    "Samburu",
    "Burgundians",
    "Mam",
    "Mocho",
    "Koeri",
    "Elamites",
    "Vandals",
    "Thyssagetae",
    "Monocoli",
    "Bilen",
    "Visigoths",
    "Kamba",
    "Grebo",
    "Persians",
    "Cappadocians",
    "Costanoan",
    "Sherbro",
    "Purépecha",
    "Vai",
    "Rajput",
    "Kumaonis",
    "Mossi",
    "Bassa",
    "Nara",
    "Boruca",
    "Anmatyerre",
    "Fon",
    "Brahui",
    "Yurok",
    "Khitans",
    "Maratha",
    "Tarahumara",
    "Lepchas",
    "Centaurs",
    "Pintupi",
    "Teruingi",
    "Jutes",
    "Daorsi",
    "Quiche",
    "Naikda",
    "Koori",
    "Melanchlaeni",
    "Vindelici",
    "Esselen",
    "Mattole",
    "Osage",
    "Mapuche",
    "Panzaleo",
    "Chumash",
    "Chola",
    "Dulebes",
    "Artibatirae",
    "Taino",
    "Crestones",
    "Elimiotae",
    "Rathwa",
    "Talares",
    "Aramaeans",
    "Arimaspi",
    "Cumans",
    "Chuj",
    "Heruli",
    "Futunans",
    "Wailaki",
    "Bessi",
    "Pohnpeian",
    "Kosraean",
    "Dii",
    "Idumeans",
    "Temne",
    "Barela",
    "Tectitec",
    "Salinan",
    "Venedi",
    "Suiones",
    "Wichita",
    "Paeonians",
    "Manchus",
    "Ngäbe",
    "Oetaeans",
    "Olmec",
    "Malinke",
    "Kushan",
    "Kachhi",
    "Isleta",
    "Kuranko",
    "Shoshone",
    "Yapese",
    "Tairona",
    "Pandya",
    "Dhanka",
    "Carpi",
    "Bhilala",
    "Xiongnu",
    "Maurya",
    "Ute",
    "Jalonke",
    "Chuukese",
    "Maya",
    "Hedareb",
    "Anangu",
    "Otoe",
    "Tolowa",
    "Durranis",
    "Kushwaha",
    "Rouran",
    "Soninke",
    "Zulu",
    "Bambara",
    "Baloch",
    "Papuans",
    "Baganda",
    "Maori",
    "Shona",
    "Xinca",
    "Maedi",
    "Vanuatuans",
    "Molossians",
    "Jicaque",
    "Goshute",
    "Warumungu",
    "Toltec",
    "Kekchi",
    "Agathyrsi",
    "Thesprotians",
    "Agrianes",
    "Sumerians",
    "Uzbeks",
    "Nazca",
    "Ghaznavids",
    "Lodh",
    "Bidyogo",
    "Kansa",
    "Odrysians",
    "Pamphylians",
    "Geloni",
    "Avars",
    "Teotihuacan",
    "Khasi",
    "Wappo",
    "Rus",
    "Chavin",
    "Paracas",
    "Kuna",
    "Chaldaeans",
    "Sandia",
    "Mayo",
    "Angles",
    "Magyars",
    "Cakchiquel",
    "Quapaw",
    "Aztec",
    "Somali",
    "Sarmatians",
    "Hupa",
    "Omaha",
    "Lunda",
    "Hopi",
    "Tojolabal",
    "Ghurids",
    "Amyctyrae",
    "Kru",
    "Khwarezmians",
    "Arawak",
    "Aenianes",
    "Tumaco",
    "Calima",
    "Dogon",
    "Satrae",
    "Myrmidons",
    "Seljuks",
    "Nepalis",
    "Kickapoo",
    "Saxons",
    "Mali",
    "Phrygians",
    "Sacapultec",
    "Algonquin",
    "Ashanti",
    "Washoe",
    "Veneti",
    "Pisidians",
    "Dan",
    "Warlpiri",
    "Autariatae",
    "Gbandi",
    "Taifals",
    "Bharwad",
    "Mughal",
    "Klamath",
    "Scordisci",
    "Somono",
    "Celts",
    "Mano",
    "Daju",
    "Argippaei",
    "Lycians",
    "Parthians",
    "Iceni",
    "Fijians",
    "Yankunytjatjara",
    "Alans",
    "Zapotec",
    "Yokuts",
    "Moabites",
    "Uspantec",
    "Golden Horde",
    "Gorkhas",
    "Ainu",
    "Siddi",
    "Triballi",
    "Mandan",
    "Androphagi",
    "Puruhá",
    "Chorotega",
    "Niuean",
    "Palawa",
    "Ponca",
    "Guarani",
    "Ilmen Slavs",
    "Tahitians",
    "Dialonke",
    "Tongans",
    "Pechenegs",
    "Susu",
    "Bhumij",
    "Kathodi",
    "Berber",
    "Marshallese",
    "Matagalpa",
    "Hasmoneans",
    "Yadava",
    "Miwok",
    "Chimu",
    "Guangala",
    "Lenca",
    "Drevlians",
    "Mongols",
    "Jama-Coaque",
    "Brigantes",
    "Torres Strait Islanders",
    "Wounaan",
    "Odomanti",
    "Shasta",
    "Pontians",
    "Phoenicians",
    "Sipacapense",
    "Arikara",
    "Iapydes",
    "Tigray",
    "Dentheletae",
    "Moesi",
    "Krahn",
    "Gepids",
    "Tajiks",
    "Timurids",
    "Jaintia",
    "Meitei",
    "Muisca",
    "Taurini",
    "Tiwi",
    "Murri",
    "Gabra",
    "Sauk",
    "Yayoi",
    "Reang",
    "Teribe",
    "Chaudhari",
    "Chichimeca",
    "Gargareans",
    "Hawaiians",
    "Tama",
    "Edoni",
    "Pelagonians",
    "Kiribati",
    "Paya",
    "Isaurians",
    "Xhosa",
    "Gautigoths",
    "Jurchens",
    "Amazons",
    "Nubians",
    "Berti",
    "Drevlyans",
    "Pokomchi",
    "Mygdones",
    "Miskito",
    "Ammonites",
    "Kassites",
    "Athamanes",
    "Fur",
    "Tzeltal",
    "Safavid",
    "Austronesians",
    "Khazars",
    "Atlanteans",
    "Cree",
    "Hidatsa",
    "Graioceli",
    "Santa Clara",
    "Radimichs",
    "Kalenjin",
    "Buyeo",
    "Palauan",
    "Wonghi",
    "Babylonians",
    "Severians",
    "Ngaanyatjarra",
    "Acoma",
    "Lake Miwok",
    "Mandinka",
    "Gupta",
    "Rama",
    "Rashaida",
    "Navajo",
    "Sciri",
    "Tivertsi",
    "Kitsai",
    "Serdi",
    "Quevedo",
    "Apache",
    "Baga",
    "Mizo",
    "Shilluk",
    "Caddo",
    "Luba",
    "Kharia",
    "Yamato",
    "Parauaei",
    "Tuvaluan",
    "Polans",
    "Turkmens",
    "Ho",
    "Chol",
    "Ho-Chunk",
    "Cook Islanders",
    "Paharis",
    "Karbi",
    "Bastarnae",
    "Cilicians",
    "Caranqui",
    "Dolopes",
    "Loma",
    "Iyrcae",
    "Rapa Nui",
    "Bribri",
    "Emishi",
    "Krivichs",
    "Sumu",
    "Sindagua",
    "Aethices",
    "Serer",
    "Yamatji",
    "Sassanids",
    "Edomites",
    "Assyrians",
    "Philistines",
    "Aguacatec",
    "Cochiti",
    "Marquesans",
    "Nicarao",
    "Balhae",
    "Rabari",
    "Samoans",
    "Potawatomi",
    "White Horde",
    "Achumawi",
    "Nuer",
    "Quillacinga",
    "Neuri",
    "Suebi",
    "Naga",
    "Wallisians",
    "Peucini",
    "Kikuyu",
    "Paiute",
    "Chontal",
    "Issedones",
    "Bulgars",
    "Jacaltec",
    "Nabataeans",
    "Pima",
    "Comanche",
    "Pawnee",
    "Sclaveni",
    "Yoruba",
    "Buyids",
    "Tripuri",
    "Pasto",
    "Cabécar",
    "Raeti",
    "San Juan",
    "Brahmin",
    "Landuma",
    "Silla",
    "Sikh",
    "Camunni",
    "Kaytetye",
    "Tiwanaku",
    "Kurmi",
    "Tuzantec",
    "Hittites",
    "Wee",
    "Ottomans",
    "Paeones",
    "Medes",
    "Santhal",
    "San Felipe",
    "Oraon",
    "Gamit",
    "Cora",
    "Menominee",
    "Slavs",
    "Getae",
    "Segusini",
    "Ewe",
    "Costoboci",
    "Punjabis",
    "Midianites",
    "Barakzais",
    "Bithynians",
    "Pygmies",
    "Canaanites",
    "Astomi",
    "Turkana",
    "Shawnee",
    "Huron",
    "Polynesians",
    "Alemanni",
    "White Croats",
    "Akan",
    "Modoc",
    "San Agustín",
    "Taos",
    "Magnetes",
    "Oromo",
    "Cherokee",
    "Maidu",
    "Santo Domingo",
    "Samanids",
    "Tierradentro",
    "Hausa",
    "Thuringii",
    "Ostrogoths",
    "Munda",
    "Ulichs",
    "Santa Ana",
    "San Ildefonso",
    "Jat",
    "Western Arrernte",
    "Miami",
    "Illini",
    "Rabinal",
    "Buzhans",
    "Scythians",
    "Sindhis",
    "Kunama",
    "Baekje",
    "Loko",
    "Nambe",
    "Arrernte",
    "Zuni",
    "Beja",
    "Chera",
    "Inca",
    "Zenú",
    "Bannock",
    "Lemurians",
    "Tlaxcaltec",
    "Picts",
    "Budini",
    "Yana",
    "Ndebele",
    "Urartians",
    "Gaya",
    "Malians",
    "Tepehuan",
    "Göktürks",
    "Amhara",
    "Tahirids",
    "Chagatais",
    "Noongar",
    "Catenates",
    "Xianbei",
    "Khoikhoi",
    "Milagro",
    "Karuk",
    "Dardani",
    "Bodo",
    "Iroquois",
    "Saini",
    "Caturiges",
    "Lombards",
    "Subtiaba",
    "Liburni",
    "Coahuiltecan",
    "Pitjantjatjara",
    "Manteño",
    "Apatani",
    "Ardiaei",
    "Bozo",
    "Tuareg",
    "Totonac",
    "Hyperboreans",
    "Tolita",
    "Patelia",
    "Saho",
    "Nogais",
    "Mende",
    "Tonkawa",
    "Bisaltae",
    "Jemez",
    "Gaels",
    "Melanesians",
    "Sinkyone",
    "Songhai",
    "Motozintlec",
    "Krim",
    "Maccabees",
    "Wintun",
    "Ziyarids",
    "Papago",
    "Greuthungi",
    "Luo",
    "Saffarids",
    "Sciapods",
    "Histri",
    "Pokomam",
    "Fox",
    "Gond",
    "Qarakhanids",
    "Thracians",
];

pub const HISTORICAL_CIVILIZATIONS: &[&str] = &[
    "Roman Empire",
    "Byzantine Empire",
    "Ottoman Empire",
    "Persian Empire",
    "Aztec Empire",
    "Mayan Empire",
    "Inca Empire",
    "Mongol Horde",
    "Carthaginian Empire",
    "Macedonian Empire",
    "Babylonian Empire",
    "Egyptian Empire",
    "Atlantis",
    "Tartaria",
    "El Dorado",
    "Lemuria",
    "Mu",
    "Shang Dynasty",
    "Sumerian Empire",
    "Viking Kingdom",
    "Assyrian Empire",
    "Holy Roman Empire",
    "Prussian Kingdom",
    "Gallic Empire",
    "Spartan City-State",
    "Athenian Republic",
    "Maurya Empire",
    "Gupta Empire",
    "Khmer Empire",
    "Abbasid Caliphate",
    "Umayyad Caliphate",
    "Mali Empire",
    "Songhai Empire",
    "Aksumite Empire",
    "Kingdom of Kush",
    "Austro-Hungarian Empire",
    "Russian Empire",
    "British Empire",
    "Spanish Empire",
    "Portuguese Empire",
    "French Empire",
    "Dutch Empire",
    "Zapotec Civilization",
    "Olmec Civilization",
    "Toltec Empire",
    "Phoenician Empire",
    "Scythian Empire",
    "Qin Dynasty",
    "Han Dynasty",
    "Tang Dynasty",
    "Ming Dynasty",
    "Qing Dynasty",
    "Kingdom of Joseon",
    "Tokugawa Shogunate",
    "Siam Kingdom",
    "Majapahit Empire",
    "Srivijaya Empire",
    "Delhi Sultanate",
    "Mughal Empire",
    // --- Expanded & Diverse Civilizations ---
    "Roman Republic",
    "Carthaginian Republic",
    "Ptolemaic Kingdom",
    "Seleucid Empire",
    "Kingdom of Pontus",
    "Kingdom of Armenia",
    "Kingdom of Epirus",
    "Kingdom of Numidia",
    "Kingdom of Pergamum",
    "Syracusan City-State",
    "Theban City-State",
    "Corinthian City-State",
    "Achaean League",
    "Aetolian League",
    "Ionian Confederacy",
    "Lydian Kingdom",
    "Phrygian Kingdom",
    "Minoan Civilization",
    "Mycenaean Civilization",
    "Kingdom of Georgia",
    "Iberian Kingdom",
    "Zhou Dynasty",
    "Sui Dynasty",
    "Song Dynasty",
    "Yuan Dynasty",
    "Go-Joseon Kingdom",
    "Kingdom of Buyeo",
    "Kingdom of Goguryeo",
    "Kingdom of Baekje",
    "Kingdom of Silla",
    "Goryeo Dynasty",
    "Kingdom of Ryukyu",
    "Yamato Kingdom",
    "Kamakura Shogunate",
    "Ashikaga Shogunate",
    "Nanzhao Kingdom",
    "Kingdom of Dali",
    "Tibetan Empire",
    "Western Xia Dynasty",
    "Liao Dynasty",
    "Jin Dynasty",
    "Chola Dynasty",
    "Chera Dynasty",
    "Pandya Dynasty",
    "Satavahana Empire",
    "Pallava Dynasty",
    "Rashtrakuta Dynasty",
    "Chalukya Dynasty",
    "Pala Empire",
    "Sena Dynasty",
    "Ghurid Dynasty",
    "Vijayanagara Empire",
    "Kingdom of Ayutthaya",
    "Kingdom of Lan Xang",
    "Kingdom of Champa",
    "Pagan Kingdom",
    "Toungoo Dynasty",
    "Konbaung Dynasty",
    "Kingdom of Sukhothai",
    "Kingdom of Thonburi",
    "Sultanate of Malacca",
    "Sultanate of Aceh",
    "Sultanate of Demak",
    "Sultanate of Mataram",
    "Sultanate of Brunei",
    "Sultanate of Sulu",
    "Kingdom of Kediri",
    "Kingdom of Singhasari",
    "Sassanid Empire",
    "Achaemenid Empire",
    "Parthian Empire",
    "Fatimid Caliphate",
    "Samanid Empire",
    "Ghaznavid Empire",
    "Seljuk Empire",
    "Safavid Empire",
    "Qajar Dynasty",
    "Zand Dynasty",
    "Hotak Dynasty",
    "Durrani Empire",
    "Kingdom of Palmyra",
    "Nabataean Kingdom",
    "Himyarite Kingdom",
    "Sabaean Kingdom",
    "Kingdom of Judea",
    "Mitanni Kingdom",
    "Urartu Kingdom",
    "Kushan Empire",
    "Hephthalite Empire",
    "Khwarazmian Empire",
    "Qara Khitai",
    "Sogdian City-States",
    "Kingdom of England",
    "Kingdom of Scotland",
    "Kingdom of Ireland",
    "Kingdom of Norway",
    "Kingdom of Denmark",
    "Kingdom of Sweden",
    "Kingdom of Poland",
    "Grand Duchy of Lithuania",
    "Polish-Lithuanian Commonwealth",
    "Tsardom of Russia",
    "Kievan Rus",
    "Novgorod Republic",
    "Kingdom of Hungary",
    "Kingdom of Bohemia",
    "Duchy of Burgundy",
    "Venetian Republic",
    "Genoese Republic",
    "Florentine Republic",
    "Kingdom of Sicily",
    "Kingdom of Naples",
    "Kingdom of Sardinia",
    "Kingdom of Castile",
    "Kingdom of Aragon",
    "Kingdom of Navarre",
    "Kingdom of Portugal",
    "Kingdom of France",
    "Angevin Empire",
    "Swiss Confederacy",
    "Duchy of Milan",
    "Kalmar Union",
    "Kingdom of Kongo",
    "Kingdom of Benin",
    "Dahomey Kingdom",
    "Ashanti Empire",
    "Oyo Empire",
    "Kanem-Bornu Empire",
    "Sokoto Caliphate",
    "Kingdom of Zimbabwe",
    "Kingdom of Mutapa",
    "Kingdom of Madagascar",
    "Kingdom of Rwanda",
    "Kingdom of Burundi",
    "Kingdom of Buganda",
    "Kingdom of Bunyoro",
    "Sultanate of Zanzibar",
    "Sultanate of Kilwa",
    "Sultanate of Adal",
    "Ajuran Sultanate",
    "Kingdom of Makuria",
    "Kingdom of Alodia",
    "Almoravid Empire",
    "Almohad Empire",
    "Marinid Sultanate",
    "Saadi Dynasty",
    "Kingdom of Nri",
    "Iroquois Confederacy",
    "Huron Confederacy",
    "Wabanaki Confederacy",
    "Powhatan Confederacy",
    "Creek Confederacy",
    "Cherokee Nation",
    "Navajo Nation",
    "Comanche Nation",
    "Apache Nation",
    "Sioux Nation",
    "Muisca Confederation",
    "Tairona Chiefdoms",
    "Chimor Kingdom",
    "Wari Empire",
    "Tiwanaku Empire",
    "Mixtec Chiefdoms",
    "Tarascan Empire",
    "Tlaxcala Republic",
    "Kingdom of Quito",
    "Kingdom of Hawaii",
    "Tuʻi Tonga Empire",
    "Kingdom of Tahiti",
    "Kingdom of Tonga",
];
