[package]
name = "sow-render"
version = "0.1.0"
edition = "2021"
description = "Shadows of War — pure GPU rendering pipelines and shaders"
license = "AGPL-3.0-or-later"

[dependencies]
blade-graphics = { workspace = true }
blade-macros = { workspace = true }
bytemuck = { workspace = true }
raw-window-handle = { workspace = true }
sow-data = { workspace = true }
sow-core = { workspace = true }
web-time = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
image = { workspace = true }
