[package]
name = "sow-render"
version = "0.1.0"
edition = "2021"
description = "Shadows of War — Blade-powered rendering engine"
license = "AGPL-3.0-or-later"

[dependencies]
sow-core = { workspace = true }
bytemuck = { workspace = true }
log = { workspace = true }
image = { workspace = true, features = ["png"] }
resvg = "0.45"
usvg = "0.45"
tiny-skia = "0.11"

blade-graphics = { workspace = true }
blade-macros = { workspace = true }
raw-window-handle = { workspace = true }
web-time = { workspace = true }


[dev-dependencies]
winit = { workspace = true }
env_logger = { workspace = true }
