[package]
name = "sow-map"
version = "0.1.0"
edition = "2024"
description = "Shadows of War Map Crate (Interactive Editor and Generator)"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
default = ["editor", "generator", "osm"]
editor = [
    "generator",
    "dep:sow-render",
    "dep:sow-ui",
    "sow-ui/map-editor",
    "sow-i18n/map-editor",
    "dep:blade-graphics",
    "dep:blade-egui",
    "dep:blade-macros",
    "dep:bytemuck",
    "dep:egui",
    "dep:winit",
]
generator = ["dep:image", "dep:brotli"]
osm = [
    "generator",
    "dep:ehttp",
    "dep:reqwest",
    "dep:tokio",
    "dep:serde",
    "dep:serde_json",
]

[dependencies]
sow-core = { workspace = true }
sow-i18n = { workspace = true }
log = { workspace = true }
bincode.workspace = true
crossbeam-channel = { workspace = true }
web-time = { workspace = true }

sow-render = { workspace = true, optional = true }
sow-ui = { workspace = true, optional = true }
blade-graphics = { git = "https://github.com/ohsalmeron/blade", rev = "0223b8faaee1f03f7566a7ea13d239b60391359d", optional = true }
blade-egui = { git = "https://github.com/ohsalmeron/blade", rev = "0223b8faaee1f03f7566a7ea13d239b60391359d", optional = true }
blade-macros = { git = "https://github.com/ohsalmeron/blade", rev = "0223b8faaee1f03f7566a7ea13d239b60391359d", optional = true }
bytemuck = { workspace = true, optional = true }
egui = { workspace = true, optional = true }
winit = { workspace = true, optional = true }
image = { workspace = true, optional = true }
brotli = { workspace = true, optional = true }
ehttp = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["rt", "rt-multi-thread"] }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
