play_tutorial = "JUGAR TUTORIAL"
single_player = "PARTIDA INDIVIDUAL"
ranked_match = "PARTIDA CLASIFICATORIA"
settings = "⚙  Opciones"
map_editor = "🗺  Editor de Mapas"
waiting_for_lobby = "Esperando datos del servidor…"
nickname_hint = "Tu apodo"
connecting = "Conectando…"
connection_error_title = "Error de Conexión"
connection_error_header = "ERROR DE CONEXIÓN"
dismiss = "DESCARTAR"
single_player_skirmish = "ESCARMUZA INDIVIDUAL"
config_simulation = "CONFIGURA TU SIMULACIÓN TÁCTICA"
map_selection = "Selección de Mapa"
bot_difficulty = "Dificultad de Bots"
tribes_count = "Cantidad de Tribus"
nations_count = "Cantidad de Naciones"
random_spawning = "Aparición Aleatoria"
simulation_speed = "Velocidad de Simulación"
no_preview = "VISTA PREVIA NO DISPONIBLE"
back = "VOLVER"
start_simulation = "INICIAR SIMULACIÓN"
no_maps_found = "No se encontraron mapas"
loading_maps = "Cargando mapas..."
matchmaking_established = "EMPAREJAMIENTO ESTABLECIDO"
awaiting_combat_criteria = "ESPERANDO CRITERIOS DE COMBATE..."
establishing_tactical_comm = "ESTABLECIENDO ENLACE TÁCTICO..."
leave_lobby = "SALIR DE LA SALA"
tactical_briefing = "INFORME TÁCTICO"
holographic_scanning = "ESCANEO HOLOGRÁFICO..."
free_for_all = "TODOS CONTRA TODOS"
team_tactics = "TÁCTICAS EN EQUIPO"
simulation = "SIMULACIÓN"
channel = "CANAL:"
slots = "RANURAS:"
lobby_channel_label = "CANAL DE LA SALA:"
max_sector_slots = "RANURAS MÁXIMAS DE SECTOR:"
deployment_engine = "MOTOR DE DESPLIEGUE:"
deployment_engine_val = "VULKAN ACTIVO"
ready_room = "SALA DE ESPERA"
ready = "LISTO"
