play_tutorial = "TUTORIAL"
single_player = "SOLO"
ranked_match = "RANKED"
settings = "⚙  Ajustes"
map_editor = "🗺  Editor"
waiting_for_lobby = "CONECTANDO"
nickname_hint = "Apodo"
connecting = "Conectando…"
connection_error_title = "Error de Conexión"
connection_error_header = "ERROR"
dismiss = "DESCARTAR"
single_player_skirmish = "ESCARMUZA"
config_simulation = "A TU GUSTO"
map_selection = "Mapa"
bot_difficulty = "Dificultad"
tribes_count = "Tribus"
nations_count = "Naciones"
random_spawning = "Aleatorio"
simulation_speed = "Velocidad"
no_preview = "NO DISPONIBLE"
back = "VOLVER"
start_simulation = "INICIAR"
no_maps_found = "Sin mapas"
loading_maps = "Cargando..."
matchmaking_established = "CONECTADO"
awaiting_combat_criteria = "BUSCANDO..."
establishing_tactical_comm = "ENLAZANDO..."
leave_lobby = "SALIR"
tactical_briefing = "INFORME"
holographic_scanning = "ESCANEO..."
free_for_all = "FFA"
team_tactics = "EQUIPOS"
simulation = "SIMULACIÓN"
channel = "CANAL:"
slots = "RANURAS:"
lobby_channel_label = "CANAL:"
max_sector_slots = "MÁX. JUG.:"
deployment_engine = "MOTOR:"
deployment_engine_val = "VULKAN"
ready_room = "ESPERA"
ready = "LISTO"
credits_link = "Créditos y licencias"
