title = "⚙  AJUSTES"
graphics_quality = "Calidad Gráfica"
audio = "Sonido"
language = "Idioma"
quality_low = "Baja"
quality_medium = "Media"
quality_high = "Alta"
mute_all = "Silenciar todo el audio"
music_volume = "Volumen de Música"
sfx_volume = "Volumen de Efectos"
back_button = "VOLVER"
credits_licenses = "Créditos y licencias"
