#!/bin/sh

# PROVIDE: sow_backfill
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="sow_backfill"
rcvar="sow_backfill_enable"

load_rc_config "${name}"

: ${sow_backfill_enable:="NO"}
: ${sow_backfill_config:="/usr/local/etc/sow-backfill.conf"}

pidfile="/var/run/${name}.pid"
child_pidfile="/var/run/${name}.child.pid"
proc="/usr/local/libexec/sow-backfill"
required_files="${proc} ${sow_backfill_config} /usr/local/share/sow/maps/world/map.bin"

. "${sow_backfill_config}"

command="/usr/sbin/daemon"
command_args="-f -P ${pidfile} -p ${child_pidfile} -r -R 5 -H -o /var/log/sow-backfill.log -T ${name} -u bizkit /usr/bin/env RUST_LOG=info ${proc} ${sow_backfill_args}"

start_precmd="${name}_prestart"

sow_backfill_prestart()
{
	touch /var/log/sow-backfill.log
	chown bizkit:bizkit /var/log/sow-backfill.log
	chmod 0640 /var/log/sow-backfill.log
}

run_rc_command "$1"
