#!/bin/sh
#
# PROVIDE: bandwidth_monitor
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="bandwidth_monitor"
rcvar="bandwidth_monitor_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} -u root /usr/local/bin/python3 /usr/local/bin/bandwidth_monitor.py"

load_rc_config $name
run_rc_command "$1"
