[package]
name = "sow-client"
version = "0.1.0"
edition = "2021"
description = "Shadows of War"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"


[dependencies]
sow-core = { workspace = true }
sow-render = { workspace = true }
blade-graphics = { workspace = true }

log = { workspace = true }
winit = { workspace = true }
sow-ui = { workspace = true }
sow-i18n = { workspace = true }
egui = { workspace = true }
blade-egui = { workspace = true }
bincode.workspace = true
sow-net = { workspace = true }
brotli = { workspace = true }
ehttp = { workspace = true, features = ["streaming"] }
crossbeam-channel = { workspace = true }
web-time = { workspace = true }
image = { workspace = true }
url = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { workspace = true }
wasm-bindgen = { workspace = true }
getrandom = { workspace = true, features = ["js"] }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
web-sys = { workspace = true, features = ["Window", "Document", "Element", "HtmlElement", "HtmlInputElement", "HtmlAnchorElement", "Navigator", "CssStyleDeclaration", "Node", "VisibilityState", "Location", "BinaryType", "Worker", "MessageEvent", "Storage", "MediaQueryList", "Blob", "Url", "BlobPropertyBag"] }
js-sys = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sow-map = { workspace = true, features = ["editor", "generator", "osm"] }
env_logger = { workspace = true }
tokio = { workspace = true }
