[package]
name = "sow-client"
version = "0.1.0"
edition = "2021"
description = "Shadows of War"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
sow-core = { workspace = true }
sow-render = { workspace = true }
blade-graphics = { workspace = true }

log = { workspace = true }
env_logger = { workspace = true }
winit = { version = "0.29.15", features = ["android-native-activity", "rwh_06"] }
sow-ui = { path = "../sow-ui" }
egui = "0.34"
blade-egui = { workspace = true }
serde_json.workspace = true
bincode.workspace = true
sow-net = { workspace = true }
brotli = "8.0.2"
ehttp = { version = "0.5.0", features = ["streaming"] }
crossbeam-channel = "0.5.15"
android_logger = "0.14"
web-time = { workspace = true }
image = { version = "0.25.10", default-features = false, features = ["webp"] }
md5 = "0.8.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.50"
wasm-bindgen = "0.2.100"
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = "0.1.7"
console_log = "1.0"
web-sys = { version = "0.3.69", features = ["Window", "Document", "HtmlElement", "Node", "VisibilityState", "Location", "BinaryType", "Worker", "MessageEvent"] }
js-sys = "0.3.69"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread"] }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.14"
libc = "0.2"

[package.metadata.android]
build_targets = ["aarch64-linux-android"]
[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[package.metadata.android.sdk]
min_sdk_version = 24
target_sdk_version = 34

[package.metadata.android.application]
label = "Shadows of War"

[package.metadata.android.application.activity]
label = "Shadows of War"
exported = true
theme = "@android:style/Theme.DeviceDefault.NoActionBar.Fullscreen"
config_changes = "density|keyboard|keyboardHidden|navigation|orientation|screenLayout|screenSize|uiMode"

[[package.metadata.android.application.activity.intent_filter]]
actions = ["android.intent.action.MAIN"]
categories = ["android.intent.category.LAUNCHER"]

[package.metadata.android.signing.release]
path = "../keystores/release.keystore"
keystore_password = "shadowswar"
key_password = "shadowswar"
key_alias = "shadows"
