[package]
name = "sow-ui"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
sow-core = { workspace = true }
sow-render = { workspace = true }
sow-net = { workspace = true }
blade-egui = { workspace = true }
blade-graphics = { workspace = true }
egui = { workspace = true }
log = { workspace = true }
web-time = { workspace = true }
image = { workspace = true }
sow-lang = { workspace = true }
