[package]
name = "sow-ui"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
sow-core = { workspace = true }
egui = { workspace = true }
log = { workspace = true }
web-time = { workspace = true }
image = { workspace = true }
sow-i18n = { workspace = true }

[features]
default = []
map-editor = ["sow-i18n/map-editor"]
